### ISSUE TITLE
Integrate TRex and ONCHAINID contracts

### ISSUE THREAD

**Issue by sruiz-vtn** [mario-eth/soldeer#100]
Hi, would be possible to add contracts from portocol [TREX](https://github.com/TokenySolutions/T-REX) and from [ONCHAINID](https://github.com/onchain-id/solidity) as dependencies to be able to fetch this contracts as we do with openzepellin contracts in a foundry project?

Thanks!!

**Comment by mario-eth** [comment]
Thanks for the request.
Added
