### ISSUE TITLE
Support Axelar contract deployment repository

### ISSUE THREAD

**Issue by robriks** [mario-eth/soldeer#102]
Opening an issue to add the axelar-contract-deployments repository which is used in tandem with the Axelar repos that already exist on Soldeer:

https://github.com/axelarnetwork/axelar-contract-deployments

**Comment by mario-eth** [comment]
Hey, as far as i can see, these are only js files. Soldeer targets only `.sol` files for now.

**Comment by robriks** [comment]
Thanks for the quick response. Didn't realize that was a constraint. How about this repo? It contains many .sol contracts, though it is also largely js focused:

https://github.com/axelarnetwork/axelar-examples/tree/main
