### ISSUE TITLE
Remappings text file created even if it's disabled

### ISSUE THREAD

**Issue by beeb** [mario-eth/soldeer#107]
It seems there is no way to disable automatic handling of remappings in soldeer 0.2.19. It used to work in 0.2.16.

There is always a `remappings.txt` file created even if I try to disable this behavior by adding a `remappings.enable = false` to either `soldeer.toml` or `foundry.toml`. Where should I put this option if I use the `foundry.toml` for configuring dependencies?

I would like to manually handle remappings inside the `foundry.toml` file, and also define dependencies inside the `foundry.toml` file.

**Comment by mario-eth** [comment]
remappings works only on on non-foundry projects. I agree that disabling remappings should be possible. Gonna work on this next, thanks for reporting.

**Comment by beeb** [comment]
I could also contribute some features if you like! I don't see a contributing guide, but are contributions welcome?

**Comment by mario-eth** [comment]
i am gonna work first on that contributing guide :D 

Yes, they are more than welcomed, I'll appreciate it. 
Feel free to join the telegram as well. 
https://t.me/+tn6gOCJseD83OTZk

**Comment by mario-eth** [comment]
I'm gonna tackle this one now.

**Comment by mario-eth** [comment]
sorry, i remember you already starting this one so i m gonna let it to you

**Comment by beeb** [comment]
No all good I didn't start yet! Also tomorrow is a holiday for me so probably won't start working on anything until Friday

**Comment by mario-eth** [comment]
https://github.com/mario-eth/soldeer/pull/112

This issue is currently developed here
