### ISSUE TITLE
Improve performance for git dependencies

### ISSUE THREAD

**Issue by beeb** [mario-eth/soldeer#122]
At the moment, the git dependencies download method performs the following:
- Clone entire repository (not recursive, no submodules)
- Git checkout to the desired rev if any
- Git rev-parse HEAD to get the checked out commit hash

If submodules are not desired, then we could maybe instead do
- a shallow clone (when no "rev" is present), but then `checkout` and `rev-parse` will not work
  - e.g. for the chainlink repo, normal cloning takes 32 seconds, shallow takes 5 seconds 
- a tree-less clone (with `--filter=tree:0`), which is faster and pulls trees as needed (so `checkout` and `rev-parse` work)
  - e.g. for the chainlink repo, tree-less takes 10 seconds
- hitting the zip file instead (at `https://github.com/owner/repo/archive/[commit].zip`)

**Comment by beeb** [comment]
Working on it, for now I added `--filter=tree:0` which seems to be the less disturbing solution.

**Comment by mario-eth** [comment]
We need to make sure it will work with tags and branches and everything that we added new

**Comment by beeb** [comment]
This has been improved by using `--filter=tree:0`. I don't think we can do much better if we want to keep supporting dependencies using git submodules for their deps (default foundry behavior).
