### ISSUE TITLE
Sanitize dependency name before creating files/folders

### ISSUE THREAD

**Issue by beeb** [mario-eth/soldeer#124]
If the dependency name (chosen by the user) contains a `/`, zip download fails as the name is not sanitize to only include filename-safe characters.

The best would probably be to sanitize the name any time we create a file or folder containing the dependency name.

**Comment by mario-eth** [comment]
Gonna start to work on this one

**Comment by mario-eth** [comment]
https://github.com/mario-eth/soldeer/pull/127
