### ISSUE TITLE
Add `openzeppelin-foundry-upgrades` dependency 

### ISSUE THREAD

**Issue by Bridgerz** [mario-eth/soldeer#130]
Currently using git submodules to install dependencies, one of them being [openzeppelin-foundry-upgrades](https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades) to manage contract upgrades. Would be great to be able to migrate dependency management to Soldeer. Thanks

**Comment by mario-eth** [comment]
hey they are already in:
https://soldeer.xyz/project/openzeppelin-foundry-upgrades

**Comment by Bridgerz** [comment]
My mistake! thanks.
