### ISSUE TITLE
`soldeer update` doesn't update

### ISSUE THREAD

**Issue by ZeroEkkusu** [mario-eth/soldeer#138]
Run:

```
soldeer install forge-std~1.9.1
soldeer update
```

Doesn't update to `1.9.2`:

```
🦌 Running soldeer update 🦌

Dependency forge-std-1.9.1 downloaded!
The dependency forge-std-1.9.1 was unzipped!
Writing forge-std~1.9.1 to the lock file.
```

<br>

Also:

It would be convenient to have `soldeer install dependency` (without `~version`) install the latest version.

**Comment by mario-eth** [comment]
soldeer update was supposed to be like a clean install, might need to be refactored to update to latest.

there is another issue for install without dependency:
https://github.com/mario-eth/soldeer/issues/103 
please comment there to keep track.

**Comment by beeb** [comment]
I'm working on refactoring the update command to update the deps
