### ISSUE TITLE
Proposal for the behavior of various sub-commands

### ISSUE THREAD

**Issue by beeb** [mario-eth/soldeer#144]
I propose the following behavior for the soldeer subcommands, which currently don't necessarily do what users expect.

- `soldeer install`: check if the lockfile is up-to-date (matches the config file) and install deps that are not already present or if mismatch with checksum/rev in the lockfile. If the lockfile diverges from the config file, we show a warning but proceed with installing lockfile deps.
- `soldeer install --clean` : same as above, but nuke the `dependencies` folder first (re-install all)
- `soldeer install package~version`: add to config+lockfile and install new dependency. Replaces existing entry if version is different.
- `soldeer update`: update each dependency in config to latest compatible version according to semver (minor and patch number can be updated, except for 0.x.x releases where only patch number can be updated). Re-install all deps to generate new lockfile.
- `soldeer update package`: update one dependency to the latest compatible version according to semver. Re-install to update lockfile entry.

I'm curious to see what everyone thinks about this, comments welcome!

**Comment by mario-eth** [comment]
I agree with all of these, it makes sense from a cli point of view.
