### ISSUE TITLE
Can't find chainlink contracts

### ISSUE THREAD

**Issue by mauricedesaxe** [mario-eth/soldeer#146]
This is the npm package in question: https://www.npmjs.com/package/%40chainlink/contracts. I'd love to contribute this if you don't have the time if it's not too hard (haven't used soldeer extensively yet so I don't know what it entails).

**Comment by mario-eth** [comment]
Hey, the chainlink contracts are added. 
Thank you for flagging it, if you have any other repo that you find useful let me know.
