### ISSUE TITLE
Feature Request: To spin out `config` as a separate crate in the workspace

### ISSUE THREAD

**Issue by TilakMaddy** [mario-eth/soldeer#152]
### Detail

To package [this](https://github.com/mario-eth/soldeer/blob/main/src/config.rs) file as a crate and expose public methods that allows other rust apps to add it as a dependency and use it for parsing `soldeer.toml` to get back a neat structure after applying all default values. 

#### Example: 
Similar to foundry's [config](https://github.com/foundry-rs/foundry/tree/master/crates/config) crate

### Interest
I'm looking to grab the remappings as a value from the `soldeer.toml` in cases where there is no actual `remappings.txt` file generated in a non-foundry project that uses soldeer as a package manager. (For foundry project, foundry's config crate helps get the remappings, so that's not an issue)

**Comment by beeb** [comment]
0.4.0 will be split into 3 crates, one of which is the `soldeer-core` crate which will expose all of the important data structures and logic to enable building on top of the tool.
