### ISSUE TITLE
each time random order in remappings.txt

### ISSUE THREAD

**Issue by macwis** [mario-eth/soldeer#181]
Each time run to update, even if the records in `remappings.txt` do not really change, their order changes. This is causing git diff in my project and unnecessary file changes for the commit.

*Actual*

Order of records in `remappings.txt` is random.

*Expected*

Order of records in `remappings.txt` is deterministic and if content does not change the lines should not be randomized.

**Comment by mario-eth** [comment]
I think this is depending on how fast they are downloading.

**Comment by maciej-specular** [comment]
ofc I can order the file manually using linux `sort` command, but imho it's good to produce deterministic results on each run - same intput should give same output, not random

**Comment by mario-eth** [comment]
Will be marked as bug to solve in 0.4.0

**Comment by beeb** [comment]
This is already fixed in 0.4.0, the remappings are sorted
