### ISSUE TITLE
Repo add request: 6551, CCIP, and Eigenlayer

### ISSUE THREAD

**Issue by peitalin** [mario-eth/soldeer#189]
Hello, would I be able to get the following repos added?

https://github.com/erc6551/reference

https://github.com/smartcontractkit/ccip

https://github.com/Layr-Labs/eigenlayer-contracts

**Comment by mario-eth** [comment]
https://soldeer.xyz/project/layr-labs-eigenlayer-contracts
https://soldeer.xyz/project/smartcontractkit-ccip
https://soldeer.xyz/project/erc6551-reference

Added.
