### ISSUE TITLE
`soldeer init` command fails on CI

### ISSUE THREAD

**Issue by pik694** [mario-eth/soldeer#216]
New `init` flow fails for flows in non-interactive flows eg. when running on CI.
Could you please provide a `--force`-like flag, so that non-interactive mode is supported.

Repro steps are visible in the following CI job: https://github.com/pik694/soldeer-init-repro/actions/runs/11325850047

**Comment by mario-eth** [comment]
Hey, we do have an issue regarding this: https://github.com/mario-eth/soldeer/issues/185 which is planned to be approached next.

**Comment by beeb** [comment]
Closed via #218
