### ISSUE TITLE
Add Pancake Swap V3 Dependencies

### ISSUE THREAD

**Issue by 0xSpraggins** [mario-eth/soldeer#217]
[`@pancakeswap/v3-core`](https://www.npmjs.com/package/@pancakeswap/v3-core)
[`@pancakeswap/v3-periphery`](https://www.npmjs.com/package/@pancakeswap/v3-periphery)

**Comment by mario-eth** [comment]
Hey, thanks for the suggestion, added! 
https://soldeer.xyz/project/@pancakeswap-v3-core
https://soldeer.xyz/project/@pancakeswap-v3-periphery
