### ISSUE TITLE
Support wildcard to match any version

### ISSUE THREAD

**Issue by beeb** [mario-eth/soldeer#223]
At the moment, there is an error when trying to e.g. `forge soldeer install "@prb-math~*"`.

I think this usage pattern should be supported so this needs fixing.

**Comment by mario-eth** [comment]
This sounds like install prb-math~latest ?

**Comment by beeb** [comment]
Not necessarily. `*` means any version now and any future version (through `update`). `latest` would probably use the latest version and pin it in the config file no?
