### ISSUE TITLE
Add chainlink-brownie-contracts

### ISSUE THREAD

**Issue by Emirhan-Cavusoglu-sftw** [mario-eth/soldeer#239]
### I have checked the following:

- [X] I have searched the issues of this repository and believe that this is not a duplicate.

### Package Name

chainlink-brownie-contracts

### Project URL

https://github.com/smartcontractkit/chainlink-brownie-contracts

### Additional Context

Some of the chainlink repos(e.g. chainlink-local) use this package could you add this?

**Comment by mario-eth** [comment]
Hey thank you,
https://soldeer.xyz/project/smartcontractkit-chainlink-brownie-contracts
deployed

**Comment by Emirhan-Cavusoglu-sftw** [comment]
that was fast :D

**Comment by mario-eth** [comment]
> that was fast :D

Soldeer was built to be fast! 🤣

**Comment by Emirhan-Cavusoglu-sftw** [comment]
This is the way 🫡
