### ISSUE TITLE
Remmappings to the foundry file

### ISSUE THREAD

**Issue by mario-eth** [mario-eth/soldeer#45]
Currently, the remappings are added to the `remappings.txt` file. 
There should be a way to add them to the `foundry.toml` config under the remappings.

**Comment by ZeroEkkusu** [comment]
Not directly related, but installing a new dependency regenerates all remappings (which are in `remapping.txt` currently).

For example, when Forge Std is installed it generates:

```
@forge-std-1.9.1=dependencies/forge-std-1.9.1
```

But let's say I change it to:

```
@forge-std=dependencies/forge-std-1.9.1/src
```

Now, when I install a next dependency, it will come back:

```
@forge-std=dependencies/forge-std-1.9.1/src
@forge-std-1.9.1=dependencies/forge-std-1.9.1
@next-dependency-1.0.0=dependencies/next-dependency-1.0.0
```

It would be nicer if it only appended new remappings, and not regenerated all.

**Comment by mario-eth** [comment]
Issue developed here https://github.com/mario-eth/soldeer/pull/112
