### ISSUE TITLE
Install dependencies of an external soldeer project

### ISSUE THREAD

**Issue by Solthodox** [mario-eth/soldeer#50]
I noticed Soldeer has a `soldeer install <dependency>` command but doesn't have a `soldeer install` one(similar to `npm install`)to install the dependencies of a already existing project that already has the Soldeer dependencies in `foundry.toml` and a `soldeer.lock` file. It would be nice having such option since `forge build`  won't work in this case.

**Comment by mario-eth** [comment]
you can use `soldeer update`, this looks in the `foundry.toml` and installs all the dependencies. 
e.g.
You `git clone` your project that has a `foundry.toml`(or `soldeer.toml`) with dependencies
You run `soldeer update`
you can run `forge build`

**Comment by Solthodox** [comment]
Oh nice, still, it's not very intuitive doing it like that, in my brain as a user first thing I try to do when installing the dependencies is run `soldeer install`.

**Comment by mario-eth** [comment]
then maybe a solution is in case there is nothing specified, just run `soldeer update`.

**Comment by anthonyra** [comment]
Coming from other javascript package managers I believe `soldeer install` is the "normal" approach. When updating a dependency it's less likely for you to update the `.toml` and more likely to do an atomic `soldeer install <dependency>`

**Comment by mario-eth** [comment]
solved
