### ISSUE TITLE
Initialize Soldeer project

### ISSUE THREAD

**Issue by Solthodox** [mario-eth/soldeer#51]
When using Soldeer it would make sense having all the packages as soldeer dependencies, including the `forge-std` that is included in `lib` by default. It would be nice to have something like `soldeer init` (similar to `npm init`) to initialize a clean Soldeer project where the `lib` folder is removed and `forge-std` is added to `dependencies`

**Comment by mario-eth** [comment]
very good idea, thanks will keep it in mind

**Comment by Solthodox** [comment]
Would love to do it myself, it should be quite easy :)

**Comment by mario-eth** [comment]
i'm open to contributors, more than that, would love more people contributing 😬 open a PR so i can review it.

**Comment by mario-eth** [comment]
this will be present in v0.2.20
