### ISSUE TITLE
feature request: native git and github support to install dependencies

### ISSUE THREAD

**Issue by zeroknots** [mario-eth/soldeer#58]
Considering potential supply chain attacks on S3, it would be great to add native git and github support to **soldeer**.

proposed CLI to add github repos directly

```
forge soldeer install github:user/repo#commithash 
forge soldeer install github:user/repo#tag
```

I think it should be trivial to parse the CLI input and allow for a more direct relationship to the dependency code

**Comment by mario-eth** [comment]
resolved in v 0.2.19
