### ISSUE TITLE
Adding Package of LayerZero Foundry Test Devtools

### ISSUE THREAD

**Issue by ShakaL0x** [mario-eth/soldeer#61]
Proposing to add contracts from [@layerzerolabs/test-devtools-evm-foundry npm package](https://www.npmjs.com/package/@layerzerolabs/test-devtools-evm-foundry) or folder in [github repo](https://github.com/LayerZero-Labs/devtools/tree/main/packages/test-devtools-evm-foundry)

Contract from this package allow to setup mock LZ contracts to test OApps locally without deployment

It will be very useful for those who don't want to use hardhat tooling provided by LZ

**Comment by mario-eth** [comment]
Hey, thanks for the suggestion.
Added: https://soldeer.xyz/project/@layerzerolabs-test-devtools-evm-foundry
Let me know if you see any other package that you feel like it should be included.
