### ISSUE TITLE
Add World ID Contracts repository to index

### ISSUE THREAD

**Issue by m1guelpf** [mario-eth/soldeer#62]
https://github.com/worldcoin/world-id-contracts

**Comment by mario-eth** [comment]
As this has no releases, i am trying to get in contact with the team to version it. 
Will keep up up to date

**Comment by dcbuild3r** [comment]
gm, sorry for the delay, was merged today by @Dzejkop: https://github.com/worldcoin/world-id-contracts/releases/tag/v1.0.0
