### ISSUE TITLE
Warning against pushing dot files `.git` `.env` etc

### ISSUE THREAD

**Issue by mario-eth** [mario-eth/soldeer#67]
There must be a warning that should alert the user when it tries to push to the central repo that it will push various common files that should not be part of like .git directory .env and so on

**Comment by Mario-SO** [comment]
Should this warning stop the `push` execution, or give the option for the user to keep pushing but without including those files?

**Comment by mario-eth** [comment]
i guess like a YES/NO prompt.
If he presses yes then proceed, otherwise stop.

Something like:

```
You are about to include some sensitive files in this version. Are you sure you want to continue?
If you are not sure what sensitive files, you can run the dry-run command to check what it will be pushed. 
```

Something like this.
