### ISSUE TITLE
.soldeerignore does not ignore some patterns after exclamation mark

### ISSUE THREAD

**Issue by ericglau** [mario-eth/soldeer#69]
My `.soldeerignore` file is based on my `.gitignore` file, which has the following from Foundry's default template:
```
!/broadcast
/broadcast/*/31337/
/broadcast/**/dry-run/
```
The expectation is that the `31337` and `dry-run` subdirectories should be ignored, even though `/broadcast` is not ignored.

However, doing a push still results in those files being included.

For example, this can be seen in the `openzeppelin-foundry-upgrades~0.3.1` package after installing it:
![Screenshot 2024-06-25 at 3 09 10 PM](https://github.com/mario-eth/soldeer/assets/29640130/9dd8f027-6d74-4498-93da-ab4b0a68f18a)

**Comment by mario-eth** [comment]
this has been solved and merged into main, will enter on the next release.
