### ISSUE TITLE
Provide dry run option for push

### ISSUE THREAD

**Issue by ericglau** [mario-eth/soldeer#70]
When pushing a new version of a package, it would be useful to have a dry run option that does not actually push to the central repository.  It could just leave a zip file that the user can inspect and test for correctness.  Or, provide an alternative command to package a zip file only.

This could help the user ensure that the are no unwanted files, that their ignore patterns are working correctly, and the user could test installing their dependency from that zip.

**Comment by mario-eth** [comment]
Will enter in the next release! thanks for the suggestion!

**Comment by ericglau** [comment]
Thanks for the quick resolution!
