### ISSUE TITLE
Add Package: Account Abstraction Packages

### ISSUE THREAD

**Issue by jamesmccomish** [mario-eth/soldeer#72]
A few common Account Abstraction packages that would be great to have in Soldeer:
- [Latest reference ERC4337 implementation](https://github.com/eth-infinitism/account-abstraction/releases/tag/v0.7.0)
- [WebAuthnSol](https://github.com/base-org/webauthn-sol/releases/tag/v1.0.0)
- [Smooth Crypto Lib](https://github.com/get-smooth/crypto-lib)
- [Latest Safe v1.4.1](https://github.com/safe-global/safe-smart-account/tree/v1.4.1)
- [Safe Test Tools](https://github.com/colinnielsen/safe-tools/releases/tag/v0.3.0)

**Comment by mario-eth** [comment]
Thank you for the recommendation, added all except Smooth Crypto lib as that does not have versioning, opened an issue.
