### ISSUE TITLE
A simple CONTRIBUTING.md would be helpful

### ISSUE THREAD

**Issue by Mario-SO** [mario-eth/soldeer#86]
A CONTRIBUTING.md to make people contribute in a standard way. You know running `cargo +nightly fmt --all --check` and `cargo +nightly clippy --workspace --all-targets --all-features` for example, plus any other thing that @mario-eth finds he is normally telling people in the PRs

**Comment by mario-eth** [comment]
This is a great idea, i've had this in the back of my mind for some time

**Comment by beeb** [comment]
Fixed in #220
