### ISSUE TITLE
Incorrect dependency format in `foundry.toml`

### ISSUE THREAD

**Issue by ZeroEkkusu** [mario-eth/soldeer#87]
`forge soldeer install` writes a dependency version string to `foundry.toml` instead of a `SoldeerDependency` struct.

Expected:

```
"@openzeppelin-contracts" = { version = "4.9.2", url = "from.where/retrieved" }
```

Actual:

```
"@openzeppelin-contracts" = "4.9.2"
```

This results in an error when `forge build` is run.

```
Error: 
failed to extract foundry config:
foundry config error: invalid type: found string "4.9.2", expected struct SoldeerDependency for setting `dependencies.@openzeppelin-contracts`
```

<br>

Don't forget to check if `forge soldeer update` still works after changing the format.

Note that installing another version of a dependency overwrites its version string in `foundry.toml`. Haven't noticed any after effects, though.

**Comment by mario-eth** [comment]
This will be fixed soon. thanks for reporting
