### ISSUE TITLE
No choice between `foundry.toml` and `soldeer.toml`

### ISSUE THREAD

**Issue by ZeroEkkusu** [mario-eth/soldeer#88]
Soldeer doesn't ask whether to use `foundry.toml`  or `soldeer.toml`.

`foundry.toml` will always be used on the first run.

**Comment by ZeroEkkusu** [comment]
It used to ask even if `foundry.toml` was present. Sounds good, then.

**Comment by mario-eth** [comment]
Yep but got feedback that if foundry is present then it will be chosen automatically to avoid any double configs by mistake.
