### ISSUE TITLE
Install dependencies on `forge build`

### ISSUE THREAD

**Issue by ZeroEkkusu** [mario-eth/soldeer#91]
Running `forge build` automatically installs git modules (`forge install`) before compiling.

It would be easier if it attempted to install Soldeer packages as well.

Running `forge soldeer install` on a codebase that doesn't use Soldeer results in an error, but in the case of `forge build` it could exit silently.

```
$ forge soldeer install
🦌 Running soldeer update 🦌

Error: 
Failed to run soldeer Could not read the config file /path/to/codebase/foundry.toml
```

**Comment by beeb** [comment]
This feature request would be best directed at the foundry project! Thanks
