### ISSUE TITLE
Publish new solmate versions

### ISSUE THREAD

**Issue by 0xJem** [mario-eth/soldeer#93]
The current version of solmate in soldeer (6.7.0) does not include the ERC6909 contract, which was added in commit `547d98b09eac04f4bf8fe0fc65a63147e99c2748`, but has had further updates to it since. It would be nice to release a version for commit `97bdb2003b70382996a79a406813f76417b1cf90`.

**Comment by 0xJem** [comment]
The ability to [specify a git commit for a dependency](https://github.com/mario-eth/soldeer/pull/94) provides a temporary workaround for this - thank you!

**Comment by mario-eth** [comment]
The ability to pull via git and ability git commit was released yesterday but it will have some modifications as per foundry requests, new version will be released today

**Comment by mario-eth** [comment]
rewritten like this to accommodate with rust way of dealing with git dep.
https://github.com/mario-eth/soldeer/pull/98

Will be released soon

**Comment by mario-eth** [comment]
this should be possible now to install via git in soldeer
