### ISSUE TITLE
Publish 0.8 variant of uniswap-v3 periphery

### ISSUE THREAD

**Issue by 0xJem** [mario-eth/soldeer#96]
This branch: https://github.com/Uniswap/v3-periphery/tree/0.8

**Comment by mario-eth** [comment]
Hey the problem with this is that it's not actually a published version which we tend to avoid transforming it into a version if it's not official. 
It is the project's job to properly manage their versions as Soldeer should not assume versions if they are not explicitly specified. 

There is a way to use that by using the git way

`soldeer install git@github.com:Uniswap/v3-periphery.git b325bb0905d922ae61fcc7df85ee802e8df5e96c`

the `b325bb0905d922ae61fcc7df85ee802e8df5e96c` commit is the latest one on that branch.

**Comment by spaceh3ad** [comment]
@mario-eth seems to not work

```sh
❯ soldeer install git@github.com:Uniswap/v3-periphery.git b325bb0905d922ae61fcc7df85ee802e8df5e96c


error: invalid value 'git@github.com:Uniswap/v3-periphery.git' for '[DEPENDENCY~VERSION]': The dependency should be in the format <DEPENDENCY>~<VERSION>
```

**Comment by mario-eth** [comment]
you have to specify a version even when you install from git

soldeer install uniswap~1.0 git@....
